# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-01 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=32, unique=True)),
                ('u_password', models.CharField(max_length=64, unique=True)),
                ('u_email', models.CharField(max_length=64, unique=True)),
                ('u_icon', models.CharField(default='', max_length=256, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_model',
            },
        ),
    ]
