# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-01 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='u_password',
            field=models.CharField(max_length=64),
        ),
    ]
