# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-01 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190701_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='u_email',
            field=models.CharField(max_length=64),
        ),
    ]
